version: 2
registries:
  Artifactory:
    type: python-index
    url: https://incloudmaster.jfrog.io/artifactory/customer-pypi-remote/
    token: ${{secrets.SHORTTOKEN_KUMAR}}
updates:
  - package-ecosystem: "pip"
    directory: "python-example/pip-example/pythonExample/"
    registries:
     - Artifactory
    schedule:
      interval: "daily"

