version: 2
registries:
  Artifactory:
    type: python-index
    url: https://incloudmaster.jfrog.io/artifactory/my-feed/pypi/manu-pypi-local/
    token: ${{secrets.DINESH}}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
     - Artifactory
    schedule:
      interval: "daily"
