version: 2
registries:
  Artifactory:
    type: npm-registry
    url: https://incloudmaster.jfrog.io/artifactory/api/pypi/manu-pypi-local/
    token: ${{secrets.DINESH}}
updates:
  - package-ecosystem: "Pypi"
    directory: "/"
    registries:
     - Artifactory
    schedule:
      interval: "daily"
