version: 2
registries:
  Artifactory:
    type: npm-registry
    url: https://incloudmaster.jfrog.io/artifactory/api/npm/customer-npm-local/
    token: ${{secrets.SHORTTOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
     - Artifactory
    schedule:
      interval: "daily"

